[package]
name = "circuit_sequencer_api"
version = "0.133.1"
edition = "2021"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/era-zkevm_circuits"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
description = "ZKsync Era circuits for EraVM"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

zk_evm = { version = "=0.133.0", path = "../zk_evm" }
bellman = { package = "zksync_bellman", version = "0" } # Not pinned to be able to update version without releasing new versions.

derivative = "2.2"
serde = {version = "1", features = ["derive"]}
rayon = "1.10"


[features]
default = []
