name: Release

on:
  push:
    branches:
      - main

jobs:

  rust-toolchain:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.rust-toolchain.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract rust toolchain version
        id: rust-toolchain
        run: echo "version=$(cat rust-toolchain)" >> "${GITHUB_OUTPUT}"

  release:
    needs: rust-toolchain
    uses: matter-labs/zksync-ci-common/.github/workflows/release-plz.yaml@v1
    secrets:
      gh_token: ${{ secrets.RELEASE_TOKEN }}
      cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK_RELEASES }}
    with:
      rust-toolchain: ${{ needs.rust-toolchain.outputs.version }}
