name: Release

# Give permissions to the release-please to open, update PRs
# and commit to PRs the repository to update Cargo.lock
permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  release:
    uses: matter-labs/zksync-ci-common/.github/workflows/release-please.yaml@v1
    secrets:
      gh_token: ${{ secrets.RELEASE_TOKEN }}
      cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK_RELEASES }}
    with:
      config: '.github/release-please/config.json'     # Specify the path to the configuration file
      manifest: '.github/release-please/manifest.json' # Specify the path to the manifest file
      update-cargo-lock: true                          # Update Cargo.lock file
      publish-to-crates-io: true                       # Enable publishing to crates.io
